### ISSUE TITLE
Taking a screenshot fails with a segfault when running headless electron

### ISSUE THREAD

**Issue by Raynos** [DevExpress/testcafe-browser-tools#192]
I am using `testcafe` with `testcafe-electron-browser-provider`

I want to run tests headless on CI. I am doing this with the following logic

```
DEBUG=testcafe:browser-provider-electron:* CI=1 xvfb-run --server-args="-screen 0 1920x1080x24" npm run testcafe
```

I am using `xvfb-run` on linux to just run a child process headless including all of electron.

Everything works great except for taking a screenshot which segfaults on linux. 

I can reproduce this both locally and on CI with the `t.takeScreenShot()` method within electron.

```
what Error: Command failed: /home/raynos/.config/npm-bin-deps/logs/node_modules/testcafe-browser-tools/bin/linux/glibc-64/resize 400001 2000 1000

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:203:13)
    at ChildProcess.EventEmitter.emit (domain.js:476:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  killed: false,
  code: null,
  signal: 'SIGSEGV',
  cmd: '/home/raynos/.config/npm-bin-deps/logs/node_modules/testcafe-browser-tools/bin/linux/glibc-64/resize 400001 2000 1000'
}
```

**Comment by Farfurix** [comment]
@Raynos 

Hello,

Screenshots, Video Recording, and Window Resizing require the [ICCCM/EWMH-compliant window manager](https://en.wikipedia.org/wiki/Comparison_of_X_window_managers) until a native browser debugging protocol (like Chrome DevTools Protocol) is used to implement such actions.

I suggest you try the following way to run your scenario:
```
xvfb-run --server-args="..." sh -c 'fluxbox & testcafe ...'
```
Here, we use the Fluxbox window manager.

Please refer to the example of using Fluxbox:  https://devexpress.github.io/testcafe/documentation/continuous-integration/travis.html#step-3---configure-travis-to-use-xvfb

Since Electron supports the Chrome DevTools protocol, we are planning to use it to implement the above actions. So, I'll close this issue in favor of https://github.com/DevExpress/testcafe-browser-provider-electron/issues/56. You can track the progress there.
