### ISSUE TITLE
Native binary for Linux ARM

### ISSUE THREAD

**Issue by Gandhi11** [DevExpress/testcafe-browser-tools#225]
Hi,

Currently testcafe is unable to take screenshot on Linux ARM.

```
Uncaught exception:

         NativeBinaryHasFailedError: The /home/jenkins/workspace/feature_migrate-dusk-to-testcafe/node_modules/testcafe-browser-tools/bin/linux/glibc-32/generate-thumbnail process failed with the 2 exit code.
         at Object.execFile (/home/jenkins/workspace/feature_migrate-dusk-to-testcafe/node_modules/testcafe-browser-tools/src/utils/exec.js:138:15)
         at default_1 (/home/jenkins/workspace/feature_migrate-dusk-to-testcafe/node_modules/testcafe-browser-tools/src/api/generate-thumbnail.js:37:5)
         at /home/jenkins/workspace/feature_migrate-dusk-to-testcafe/node_modules/testcafe/src/screenshots/capturer.js:187:17
         at Capturer._capture (/home/jenkins/workspace/feature_migrate-dusk-to-testcafe/node_modules/testcafe/src/screenshots/capturer.js:144:9)
         at Capturer.captureAction (/home/jenkins/workspace/feature_migrate-dusk-to-testcafe/node_modules/testcafe/src/screenshots/capturer.js:212:16)
         at BrowserManipulationQueue._executeCommand (/home/jenkins/workspace/feature_migrate-dusk-to-testcafe/node_modules/testcafe/src/test-run/browser-manipulation-queue.js:61:24)
         at BrowserManipulationQueue.executePendingManipulation (/home/jenkins/workspace/feature_migrate-dusk-to-testcafe/node_modules/testcafe/src/test-run/browser-manipulation-queue.js:102:24)
         at TestRun.ready-for-browser-manipulation (/home/jenkins/workspace/feature_migrate-dusk-to-testcafe/node_modules/testcafe/src/test-run/index.ts:1657:22)
         at TestRun.handleServiceMessage (/home/jenkins/workspace/feature_migrate-dusk-to-testcafe/node_modules/testcafe-hammerhead/lib/session/index.js:62:20)
         at Proxy._onServiceMessage (/home/jenkins/workspace/feature_migrate-dusk-to-testcafe/node_modules/testcafe-hammerhead/lib/proxy/index.js:144:32)

         Browser: Chrome 109.0.5414.119 / Linux 0.0
    
```

Here is the output of `uname -a`
```
Linux localhost 5.15.0-1030-aws #34~20.04.1-Ubuntu SMP Tue Jan 24 15:16:39 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
```

Would it be possible to add Linux ARM binary?

I can help with testing if needed.
Thanks

**Comment by Dmitry-Ostashev** [comment]
Hello,

Could you please clarify what device you use for running TestCafe tests? Is it Raspberry Pi or something like that?

We do not plan full support for Arm64. However, we may consider it in the future.

**Comment by miherlosev** [comment]
Hi @pgrenaud,

Thank you for sharing this information. At present, we don't see much interest in this capacity from the TestCafe community. Unfortunately, we cannot commit to its development. If it is very important for you, feel free to share your PR.

**Comment by RInverid** [comment]
Hi @miherlosev , we are also experiencing this issue. for unrelated reasons we were unable to update testcafe for a long time, and are now doing a big jump from 1.18.0 to 3.6.0.

However, most of our developers run on Mac M# devices, which are ARM devices. Running native this works just fine, but when running our entire test suite we use docker, which is linux, which causes us to run into this issue.

Please reconsider working on this ticket, I think this will be a more common issue as the world slowly moves to ARM (see the new Snapdragon X Series, which ios the start of a big windows on ARM push as well)

**Comment by Bayheck** [comment]
Thank you for sharing this information. 

Unfortunately, we cannot take this enhancement into work because at present we are fully focused on other tasks. We may reconsider the priority of this task in the future if we get enough requests for it. If it is very important for your project, feel free to share your PR.
